# Generated by Django 4.2.4 on 2023-08-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizacion'),
        ),
    ]
